#!/usr/bin/env sh
# Install/update project dependencies
# -u for update

while getopts :u flag; do
	case "${flag}" in
	u) UPDATE='--lock-write' ;;
	esac
done

# Prelude
_required_ "deno direnv" || exit

LOCKFILE=$(touch "$ROOT/deno.lock" && echo "--lock $_")
# Add packages
#deno install -qAf --unstable $LOCKFILE $UPDATE https://deno.land/x/denon/denon.ts
#deno install --unstable --allow-read --allow-write --allow-net --allow-env --name bundler https://deno.land/x/bundler/cli.ts
echo -e ""
direnv allow
